### ISSUE TITLE
With default settings window can not be brought back from the tray

### ISSUE THREAD

**Issue by bertfrees** [daisy/pipeline-ui#96] opened 2023-03-06 15:27 UTC
This is related to https://github.com/daisy/pipeline-ui/issues/74. On macOS, now when the window is closed it can not be brought back except through launching the application again. The tray menu is all greyed out (and the app is not visible in the dock, which is intended). Launching the application again will result in the "The application can keep running in the tray" message. When "remember this decision" is chosen it will work fine the next time.

**Comment by marisademeglio** [comment] 2023-03-06 17:33
I can't reproduce this on mac. What are the exact steps? You start it and it uses the default settings ("ask when closing the window"). Then what?

**Comment by bertfrees** [comment] 2023-03-07 08:26
- Start it
- Check that it uses default settings ("ask when closing the window" and "Close all non-running jobs")
- Close window
- Click tray icon

All the item are now greyed out.

- Launch application again

You get the dialog now which you should have gotten when you closed the window.

- Choose "Cancel"

The items in the tray menu can now be selected.

**Comment by rdeltour** [comment] 2023-03-08 15:50
Yeah, got this too, could reproduce with Bert's steps.

**Comment by NPavie** [comment] 2023-03-15 13:26
So i was able to reproduce the "all greyed" tray menu, but it was because the dialog asking if the app should be closed or kept open was opened.
As soon as i close the dialog, the tray menu is not greyed anymore.

What I think here is that on macOS, when electron opens a dialog without any specific window bound to it, it seems to go up in the UI tree of the app, so it is greying the tray on macOS, but it is also blocking the settings window if it is opened when i test it.
(It does not behave like this on Windows : the tray menu remains fully usable with the dialog opened).

Si i think it's possibly normal behavior on MacOS with Electron ad Alert dialog without linking the dialog to a specific window.

This can be mitigated by not closing the window until user is selecting an action and binding the dialog to the window : 
If i do this, the tray remain usable on MacOS and only the main window is greyed out.

**Closed** 2023-03-15 19:57 UTC
