### ISSUE TITLE
TTS should optionally process alt text too

### ISSUE THREAD

**Issue by marisademeglio** [daisy/pipeline-ui#193] opened 2024-02-06 00:05 UTC
From recent tester feedback:

"When adding TTS in a conversion, offer the option to include the alt text (like we see with some readloud experiences)."

**Comment by bertfrees** [comment] 2024-02-06 10:30
@marisademeglio Shall I transfer this issue to the pipeline-modules repo?

**Comment by marisademeglio** [comment] 2024-04-16 18:18
Has this been transferred and can we close it here?

**Comment by bertfrees** [comment] 2024-04-17 10:49
Is this a duplicate of https://github.com/daisy/pipeline-modules/issues/84?

**Closed** 2024-04-17 15:55 UTC
Labels: engine, propose-to-close
