### ISSUE TITLE
Integer inputs are not updating in some scripts

### ISSUE THREAD

**Issue by bertfrees** [daisy/pipeline-ui#80] opened 2023-02-27 10:23 UTC
The "Cancel job" menu item in the "File" menu seems to be always disabled (not selectable).

**Comment by bertfrees** [comment] 2023-02-27 10:39
Hmm, I can not reproduce this anymore, but am sure that this was the case at one point. Even when a job tab was selected that was cancelable with a button.

I've also experienced some other behavior that I can not reproduce right now. (These are potentially all separate issues but I'm listing them here now.)

- "New job" in tray menu did not work
- Integer input fields did not work (could not enter anything with keyboard, and up/down arrows did not work) (In my test it was the "Chunk size" option of "DAISY 3 to EPUB 3" I believe.)

**Comment by NPavie** [comment] 2023-02-27 16:42
The empty windows issues is normally fixed by c5c78ae896c7069d38b2f3ef9aa43f3ad27f6918

**Comment by NPavie** [comment] 2023-02-27 16:42
Problem with the integer input field confirmed, i'll check it

**Comment by NPavie** [comment] 2023-03-02 15:31
Hum, I'm not sure the issue is still there in dev : 
I tried to reproduce the error in dev for some time today but i did not get the behavior i had last time (the chunck field staying on the -1 value).

It might have been fixed by the migration of the job request preparation in the backend in 017cd5aab2382da8f75b190f78ff2cd39e98a27f but i'm not 100% sure.

We might need to check if the issue still appears in other cases after the next release.

**Closed** 2023-03-02 21:39 UTC
