### ISSUE TITLE
Window can not be brought back from the tray when application is quit while jobs are running

### ISSUE THREAD

**Issue by bertfrees** [daisy/pipeline-ui#125] opened 2023-03-16 17:31 UTC
Very similar to https://github.com/daisy/pipeline-ui/issues/96.

When the application is quit while jobs are running, the window closes and the tray stays active but the window can not be brought back from the tray (all items grey). Only by relaunching the application you can bring the window back, in which case the "Some jobs are still running in the engine" warning will appear.

**Comment by bertfrees** [comment] 2023-03-16 18:20
Well you could not reproduce #96 either, so maybe logical that you can't reproduce this one. But I'll add the steps...

**Comment by marisademeglio** [comment] 2023-03-16 19:25
So with ⌘H, you're hiding the window, but I wouldn't say it's the same as quitting the application (⌘Q). 

But still I get different results than you. The tray menu is not ever grayed out again.

Whether I re-enter the application from the mac dock or use the /Applications shortcut, I get a window for the job that's still in progress. 

When I try to say Tray->Open Window, nothing happens. But I think that's a different behavior entirely.

**Comment by bertfrees** [comment] 2023-03-16 19:26
Sorry! I meant ⌘Q.

**Comment by NPavie** [comment] 2023-03-17 19:52
I tried to reproduced the issue : 
- I always have the dialog on closing while having running jobs
- The greyed tray menu is due to a dialog being opened by the app somewhere on the system without being bound to a window (same as #96, but I think ⌘Q might goes to a different path)

I'll look into it

**Comment by NPavie** [comment] 2023-03-17 20:26
Ok I think I found out how to fix that.
It is indeed like for #96 (just a different dialog).
I'll fix this behaviour when the window is opened, but in case of quitting the app from the tray with the window already closed, there is no way to change this particular behaviour.

(I think it is macOS default behaviour to block interactions on a app when a dialog not bound to a window is raised, to ensure user does not miss critical inputs)

I'm not sure on why you don't have the dialog displayed every time though, but it might have been placed in a specific workspace.

**Closed** 2023-03-17 21:17 UTC
